NAME = Old

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = MHCertificateAdditions.h

MFILES = MHCertificateAdditions.m

PUBLIC_HEADERS = MHCertificateAdditions.h

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
