NAME = MAPM_tst

PROJECT_TYPE = Component
MAKEFILE = subproj.make

CFILES = mapm_validate.c

HEADER_PATHS = -I.. -I../../MSCore_src -I../../MSCore_src/MAPM_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
