NAME = MAPM_tst

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = mapm_validate.h

CFILES = mapm_validate.c

PUBLIC_HEADERS = mapm_validate.h

HEADER_PATHS = -I../../MSCore_src -I../../MSCore_src/MAPM_src -I../../MSFoundation_Basics_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
