NAME = MSCore_tstm

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = 

MFILES = mscore_test.m

HEADER_PATHS = -I../MSCore_src -I../MSCore_tst

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
