NAME = MSCore_tstm

PROJECT_TYPE = Component
MAKEFILE = subproj.make

MFILES = mscore_test.m

HEADER_PATHS = -I../MSCore_src -I../MSCore_src/MAPM_src -I../MSCore_tst -I../MSFoundation_Basics_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
