NAME = MSMySQLAdaptor

PROJECT_TYPE = Loadable Bundle
MAKEFILE = bundle.make

SUBPROJECTS = MSMySQLAdaptor

PROJECTVERSION = 2.8
CODE_GEN_STYLE = DYNAMIC
MAKEFILEDIR = $(MAKEFILEPATH)/pb_makefiles
WINDOWS_BUILD_OUTPUT_DIR = $(WORKINGFOLDER)/Library/Builds/MicroStep

include wo451.make
include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
