NAME = MSCore_tst

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = mscore_validate.h

CFILES = mscore_carray_validate.c

HEADER_PATHS = -I../MSCore_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
