NAME = MSCore_src

PROJECT_TYPE = Component
MAKEFILE = subproj.make

SUBPROJECTS = MAPM_src

HFILES = MSCArray.h MSCBuffer.h MSCColor.h MSCCouple.h MSCDate.h MSCDecimal.h MSCDictionary.h MSCObject.h MSCString.h MSCore.h MSCoreIncludes.h MSCoreSES.h MSCoreSystem.h MSCoreSystemWin32.h MSCoreTools.h MSCoreTypes.h MSCoreUnichar.h MSCoreUnicharPrivate.h MSCore_Private.h MSTE.h

CFILES = MSCArray.c MSCBuffer.c MSCColor.c MSCCouple.c MSCDate.c MSCDecimal.c MSCDictionary.c MSCObject.c MSCString.c MSCoreSES.c MSCoreSystem.c MSCoreSystemWin32.c MSCoreTools.c MSCoreToolsCompress.c MSCoreUnichar.c MSTE.c

PUBLIC_HEADERS = MSCArray.h MSCBuffer.h MSCColor.h MSCCouple.h MSCDate.h MSCDecimal.h MSCDictionary.h MSCObject.h MSCString.h MSCore.h MSCoreIncludes.h MSCoreSES.h MSCoreSystem.h MSCoreSystemWin32.h MSCoreTools.h MSCoreTypes.h MSCoreUnichar.h MSTE.h

HEADER_PATHS = -I../MSFoundation_Basics_src -IMAPM_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
