NAME = MSTE_tst

PROJECT_TYPE = Component
MAKEFILE = subproj.make

CFILES = mste_test.c mste_validate.c

HEADER_PATHS = -I.. -I../../MSCore_src -I../../MSCore_src/MAPM_src -I../../MSCore_src/MSTE_src -I../../MSFoundation_Basics_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
