NAME = MSCore_tstc

PROJECT_TYPE = Component
MAKEFILE = subproj.make

CFILES = mscore_test.c

HEADER_PATHS = -I../MSCore_src -I../MSCore_src/MAPM_src -I../MSCore_tst

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
