NAME = MSFoundation_src

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = MSFoundation.h MSArray.h MSMutableArray.h\
         MSUnicodeBuffer.h

MFILES = MSCObject.m\
         MSArray.m MSMutableArray.m\
         MSUnicodeBuffer.m

HEADER_PATHS = -I../MSCore_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
