NAME = MSPostgresAdaptor

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = MSPostgresConnection.h MSPostgresResultSet.h MSPostgresTransaction.h

MFILES = MSPostgresConnection.m MSPostgresResultSet.m MSPostgresTransaction.m

PUBLIC_HEADERS = MSPostgresConnection.h MSPostgresResultSet.h MSPostgresTransaction.h

HEADER_PATHS = -I../../MSCore_src -I../../MSCore_src/MAPM_src -I../../MSFoundation_Basics_src -I../../MSFoundation_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
