NAME = MSTE_src

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = CBuffer.h Json.h JsonLex.h JsonLexTk.h MSTDecoderr.h MSTE_Private.h MSTHeader.h MSTObjBuilder.h MSTReader.h MSTReaderTk.h MSTType.h

CFILES = CBuffer.c JsonLex.c JsonLexTk.c MSTDecoderr.c MSTHeader.c MSTObjBuilder.c MSTReader.c

PUBLIC_HEADERS = CBuffer.h Json.h JsonLex.h JsonLexTk.h MSTDecoderr.h MSTHeader.h MSTObjBuilder.h MSTReader.h MSTReaderTk.h MSTType.h

HEADER_PATHS = -I.. -I../../MSFoundation_Basics_src -I../MAPM_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
