NAME = MSFoundation_tst

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = msfoundation_validate.h

MFILES = msfoundation_array_validate.m msfoundation_buffer_validate.m msfoundation_color_validate.m msfoundation_couple_validate.m msfoundation_date_validate.m msfoundation_decimal_validate.m msfoundation_dictionary_validate.m msfoundation_mste_validate.m msfoundation_string_validate.m msfoundation_test.m

PUBLIC_HEADERS = msfoundation_validate.h

HEADER_PATHS = -I../MSCore_src -I../MSCore_src/MAPM_src -I../MSCore_tst -I../MSFoundation_Basics_src -I../MSFoundation_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
