NAME = MSFoundation_tst

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = msfoundation_validate.h

MFILES = msfoundation_test.m msfoundation_array_validate.m msfoundation_buffer_validate.m

HEADER_PATHS = -I../MSCore_src -I../MSCore_tst -I../MSFoundation_Basics_src -I../MSFoundation_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
