NAME = MHServer_src

PROJECT_TYPE = Component
MAKEFILE = subproj.make

MFILES = MASHServer_main.m

HEADER_PATHS = -I../MHMessenger_src -I../MHRepositoryServer_src -I../MSCore_src -I../MSCore_src/MAPM_src -I../MSFoundation_Basics_src -I../MSFoundation_src -I../MSNet_src -I../MSNet_src/Crypto_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
