NAME = MSMySQLAdaptor

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = MSMySQLAdaptorKit.h MSMySQLConnection.h MSMySQLResultSet.h MSMySQLTransaction.h

MFILES = MSMySQLConnection.m MSMySQLResultSet.m MSMySQLTransaction.m

PUBLIC_HEADERS = MSMySQLAdaptorKit.h MSMySQLConnection.h MSMySQLResultSet.h MSMySQLTransaction.h

HEADER_PATHS = -I../../MSCore_src -I../../MSCore_src/MAPM_src -I../../MSDb_src -I../../MSFoundation_Basics_src -I../../MSFoundation_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
