NAME = MSFoundation_Basics_src

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = MSASCIIString.h MSBool.h MSCNaturalArray.h MSCSSLInterface.h MSCharsets_Private.h MSCoderAdditions.h MSExceptionAdditions.h MSFileManipulation.h MSFoundationDefines.h MSLanguage.h MSMutex.h MSNaturalArray.h MSNaturalArrayEnumerator.h MSNaturalArrayEnumerator_Private.h MSObjectAdditions.h MSSSLInterface.h MSStringParsing.h MSStringParsing_Private.h MSTDecoder.h MSTEncoder.h

MFILES = MSASCIIString.m MSBool.m MSCNaturalArray.m MSCSSLInterface.m MSCharsets_Private.m MSCoderAdditions.m MSExceptionAdditions.m MSFileManipulation.m MSLanguage.m MSMutex.m MSNaturalArray.m MSNaturalArrayEnumerator.m MSObjectAdditions.m MSSSLInterface.m MSStringParsing.m MSTDecoder.m MSTEncoder.m

PUBLIC_HEADERS = MSASCIIString.h MSBool.h MSCNaturalArray.h MSCSSLInterface.h MSCoderAdditions.h MSExceptionAdditions.h MSFileManipulation.h MSFoundationDefines.h MSLanguage.h MSMutex.h MSNaturalArray.h MSNaturalArrayEnumerator.h MSObjectAdditions.h MSSSLInterface.h MSStringParsing.h MSTDecoder.h MSTEncoder.h

HEADER_PATHS = -I../3rdparty/wo451/include -I../MSCore_src -I../MSCore_src/MAPM_src -I../MSDBAdaptors_src/MSSQLCipherAdaptor/sqlcipher -I../MSFoundation_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
