NAME = MSFoundation_Basics_src

PROJECT_TYPE = Component
MAKEFILE = subproj.make

HFILES = MSFoundationDefines.h MSCoderAdditions.h MSExceptionAdditions.h

MFILES = MSCoderAdditions.m MSExceptionAdditions.m

HEADER_PATHS = -I../MSCore_src -I../MSFoundation_src

include $(MAKEFILEDIR)/platform.make
include $(MAKEFILEDIR)/$(MAKEFILE)
